In [154]:
import numpy as np
import pandas as pd

## Data Types and Attributes

In [155]:
# main datatype is ndarray
a1 = np.array([1,2,3])

In [156]:
type(a1)

numpy.ndarray

In [157]:
a2 = np.array([[1.5,2,3.3],
                [4.5,6.3,1.3]])

In [158]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [159]:
a2

array([[1.5, 2. , 3.3],
       [4.5, 6.3, 1.3]])

In [160]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [161]:
# shape
a1.shape

(3,)

In [162]:
a2.shape

(2, 3)

In [163]:
a3.shape

(2, 3, 3)

In [164]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [165]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [166]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [167]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [168]:
# Create DataFrame from numpy array
df = pd.DataFrame(a2)
df

0    1    2
0  1.5  2.0  3.3
1  4.5  6.3  1.3

## Creating Arrays

In [169]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [170]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [171]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [172]:
rand_array = np.random.randint(0,10,size=(2,3,3))
rand_array

array([[[6, 8, 2],
        [3, 0, 0],
        [6, 0, 6]],

       [[3, 3, 8],
        [8, 8, 2],
        [3, 2, 0]]])

In [173]:
rand_array2 = np.random.random((5,3))
rand_array2

array([[0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901],
       [0.44712538, 0.84640867, 0.69947928],
       [0.29743695, 0.81379782, 0.39650574],
       [0.8811032 , 0.58127287, 0.88173536]])

In [174]:
rand_array3 = np.random.rand(5,3)
rand_array3

array([[0.69253159, 0.72525428, 0.50132438],
       [0.95608363, 0.6439902 , 0.42385505],
       [0.60639321, 0.0191932 , 0.30157482],
       [0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233]])

In [175]:
# Pseudo-random numbers
np.random.seed(seed=435113)
rand_array_4 = np.random.randint(0,10,(5,3))
rand_array_4

array([[7, 7, 1],
       [2, 3, 7],
       [7, 1, 9],
       [3, 7, 9],
       [5, 2, 4]])

In [176]:
np.random.seed(seed=435113)
rand_array_5 = np.random.randint(0,10,(5,3))
rand_array_5

array([[7, 7, 1],
       [2, 3, 7],
       [7, 1, 9],
       [3, 7, 9],
       [5, 2, 4]])

## Viewing Arrays and Matrices

In [177]:
np.unique(rand_array_5)

array([1, 2, 3, 4, 5, 7, 9])

In [178]:
a1[0]

1

In [179]:
a2[0]

array([1.5, 2. , 3.3])

In [180]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [181]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [182]:
# 4+ dimensional
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 4, 4, 6, 4],
         [1, 7, 0, 5, 4],
         [4, 7, 4, 4, 3],
         [2, 3, 5, 2, 8]],

        [[8, 1, 6, 4, 9],
         [0, 0, 6, 9, 8],
         [7, 9, 3, 6, 7],
         [2, 1, 4, 1, 7]],

        [[3, 3, 0, 3, 7],
         [0, 7, 5, 0, 3],
         [4, 1, 9, 4, 7],
         [6, 7, 2, 7, 4]]],


       [[[2, 5, 8, 1, 2],
         [9, 4, 4, 6, 3],
         [9, 2, 4, 4, 1],
         [9, 8, 1, 7, 2]],

        [[2, 1, 4, 6, 5],
         [3, 2, 7, 7, 9],
         [5, 1, 4, 1, 8],
         [5, 4, 2, 7, 9]],

        [[8, 1, 3, 7, 1],
         [0, 8, 1, 6, 2],
         [0, 4, 2, 7, 1],
         [2, 5, 7, 1, 0]]]])

In [183]:
# get first 4 numbers of innermost arrays
a4[:,:,:,:4]

array([[[[9, 4, 4, 6],
         [1, 7, 0, 5],
         [4, 7, 4, 4],
         [2, 3, 5, 2]],

        [[8, 1, 6, 4],
         [0, 0, 6, 9],
         [7, 9, 3, 6],
         [2, 1, 4, 1]],

        [[3, 3, 0, 3],
         [0, 7, 5, 0],
         [4, 1, 9, 4],
         [6, 7, 2, 7]]],


       [[[2, 5, 8, 1],
         [9, 4, 4, 6],
         [9, 2, 4, 4],
         [9, 8, 1, 7]],

        [[2, 1, 4, 6],
         [3, 2, 7, 7],
         [5, 1, 4, 1],
         [5, 4, 2, 7]],

        [[8, 1, 3, 7],
         [0, 8, 1, 6],
         [0, 4, 2, 7],
         [2, 5, 7, 1]]]])

## Manipulating and Comparing Arrays

In [184]:
a1

array([1, 2, 3])

In [185]:
ones = np.ones(3)

In [186]:
a1 + ones

array([2., 3., 4.])

In [187]:
a1 * (2*ones)

array([2., 4., 6.])

In [188]:
#multiplying different dimensions
a1 * a2

array([[ 1.5,  4. ,  9.9],
       [ 4.5, 12.6,  3.9]])

In [189]:
a2 / a1

array([[1.5       , 1.        , 1.1       ],
       [4.5       , 3.15      , 0.43333333]])

In [190]:
#Floor division
a2 // a1

array([[1., 1., 1.],
       [4., 3., 0.]])

In [191]:
# Exponents
a2 ** 2

array([[ 2.25,  4.  , 10.89],
       [20.25, 39.69,  1.69]])

In [192]:
np.square(a2)

array([[ 2.25,  4.  , 10.89],
       [20.25, 39.69,  1.69]])

In [193]:
a1 % 2

array([1, 0, 1])

In [194]:
a1

array([1, 2, 3])

In [195]:
# gets exponential
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [196]:
#gets log
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [197]:
a2

array([[1.5, 2. , 3.3],
       [4.5, 6.3, 1.3]])

In [198]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Aggregation

- performing same operation on number of things

In [199]:
list = [1,2,3]

In [200]:
# use sum() for python datatypes
# use np.sum() for numpy arrays (much faster for numerical calculations on arrays/matrices)

In [201]:
big_array = np.random.random(10000)
big_array[:10]

array([0.19920293, 0.42364703, 0.91561487, 0.23835655, 0.39773683,
       0.31540809, 0.91685621, 0.41184499, 0.9788804 , 0.10720345])

In [202]:
#timing
%timeit sum(big_array)
%timeit np.sum(big_array)

1.32 ms ± 34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.16 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [203]:
np.mean(a2)


3.1500000000000004

In [204]:
np.max(a2)
np.min(a2)

1.3

In [205]:
np.std(a2)

1.7904841058588967

In [206]:
np.var(a2)

3.205833333333333

In [207]:
# Demo for standard dev. and variance
high_var_array = [1,2,100,200,4000,5000]
low_var_array = [1,4,6,8,10]

In [208]:
np.var(high_var_array)

4437617.25

In [209]:
np.var(low_var_array)

9.76

In [210]:
np.std(high_var_array)

2106.565273140142

In [211]:
np.std(low_var_array)

3.1240998703626617

## Reshape and Transpose

In [212]:
a2

array([[1.5, 2. , 3.3],
       [4.5, 6.3, 1.3]])

In [213]:
a2.shape

(2, 3)

In [214]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [215]:
a3.shape

(2, 3, 3)

In [216]:
a2 = a2.reshape(2,3,1)

In [217]:
a2 * a3

array([[[ 1.5,  3. ,  4.5],
        [ 8. , 10. , 12. ],
        [23.1, 26.4, 29.7]],

       [[45. , 49.5, 54. ],
        [81.9, 88.2, 94.5],
        [20.8, 22.1, 23.4]]])

In [218]:
# Transpose
a2 = a2.reshape(2,3)
a2

array([[1.5, 2. , 3.3],
       [4.5, 6.3, 1.3]])

In [219]:
a2.T

array([[1.5, 4.5],
       [2. , 6.3],
       [3.3, 1.3]])

In [220]:
a2.T.shape

(3, 2)

## Dot Product

In [221]:
np.random.seed(0)

array1 = np.random.randint(10, size=(5,3))
array2 = np.random.randint(10, size=(5,3))

In [222]:
array1, array2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [223]:
# Element wise multiplication
array1 * array2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [224]:
array2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [225]:
# Dot product (same thing as product of array and transpose)
# inside dimensions must match
np.dot(array1, array2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot Product Example

In [226]:
jars_sold = np.random.randint(20, size=(5,3))
jars_sold

array([[18,  3, 17],
       [19, 19, 19],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11]])

In [227]:
weekly_sales = pd.DataFrame(jars_sold, 
                            index=['Mon','Tue','Wed','Thur','Fri'], 
                            columns=['Almond','Peanut','Cashew'])
weekly_sales

Almond  Peanut  Cashew
Mon       18       3      17
Tue       19      19      19
Wed       14       7       0
Thur       1       9       0
Fri       10       3      11

In [228]:
prices = np.array([10,8,12])

In [229]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Price'], columns=['Almond','Peanut','Cashew'])
butter_prices

Almond  Peanut  Cashew
Price      10       8      12

In [230]:
daily_rev = butter_prices.dot(weekly_sales.T)

In [231]:
daily_rev

Mon  Tue  Wed  Thur  Fri
Price  408  570  196    82  256

In [232]:
# add daily revenue as column to weekly sales dataframe
weekly_sales

Almond  Peanut  Cashew
Mon       18       3      17
Tue       19      19      19
Wed       14       7       0
Thur       1       9       0
Fri       10       3      11

In [233]:
weekly_sales["Total Rev ($)"] = daily_rev.T
weekly_sales

Almond  Peanut  Cashew  Total Rev ($)
Mon       18       3      17            408
Tue       19      19      19            570
Wed       14       7       0            196
Thur       1       9       0             82
Fri       10       3      11            256

## Comparison Operators

In [234]:
a1, a2

(array([1, 2, 3]),
 array([[1.5, 2. , 3.3],
        [4.5, 6.3, 1.3]]))

In [235]:
bool_array = a1 > a2
bool_array

array([[False, False, False],
       [False, False,  True]])

In [236]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [237]:
a1 == a1

array([ True,  True,  True])

In [238]:
a1 == a2

array([[False,  True, False],
       [False, False, False]])

## Sorting Arrays

In [239]:
random = np.random.randint(10, size=(3,5))
random

array([[2, 7, 2, 0, 0],
       [4, 5, 5, 6, 8],
       [4, 1, 4, 9, 8]])

In [240]:
# sort each row in array
random.sort()
random

array([[0, 0, 2, 2, 7],
       [4, 5, 5, 6, 8],
       [1, 4, 4, 8, 9]])

In [241]:
random = np.random.randint(10, size=(3,5))
random

array([[1, 1, 7, 9, 9],
       [3, 6, 7, 2, 0],
       [3, 5, 9, 4, 4]])

In [242]:
# argsort replace top row with index values
np.argsort(random)

array([[0, 1, 2, 3, 4],
       [4, 3, 0, 1, 2],
       [0, 3, 4, 1, 2]])

In [243]:
# argmin gets index of min value based on axis (opposite for argmax)
# axis 1 = by row, axis 0 = by column
np.argmin(random, axis=0)

array([0, 0, 0, 1, 1])

In [244]:
np.argmax(random, axis=1)

array([3, 2, 2])

## Practical Example: Images

<img src="panda.png" />

In [252]:
from matplotlib.image import imread
panda = imread("panda.png")
type(panda)

numpy.ndarray

In [253]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [254]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.